### ISSUE TITLE
Can Not Find yaml When Running Examples

### ISSUE THREAD

**Issue by Cfather** [ToyotaResearchInstitute/idto#28]
Hi, 

I met an issue that the program can not find configuration yaml file after compiling with bazel. Here's the output:

```
[2024-06-28 23:29:33.160] [console] [info] Meshcat listening for connections at http://localhost:7000
terminate called after throwing an instance of 'std::runtime_error'
  what():  Sought 'idto/examples/spinner/spinner.yaml' in runfiles directory '/home/username/.cache/bazel/_bazel_username/0ae31a949d67f5a9e59be457bc34081b/execroot/_main/bazel-out/k8-opt/bin/examples/spinner/spinner.runfiles' and it is on the manifestbut the file does not exist at that location; perhaps a 'data = []' dependency is missing.
```

Could anyone help me with this? Did I run anything wrong? Thanks!

**Comment by vincekurtz** [comment]
Try downgrading bazel to version 6.3.1.

I don't think this is anything you've done wrong. Something about how the config files are located broke when Drake updated to bazel 7, which I assume you have from the Drake `install_prereqs` script. We're working on a more permanent fix, but for now downgrading bazel is the hacky workaround

**Comment by Cfather** [comment]
Thanks. This solved my problem!
